"""add remember_me to sessions

Revision ID: 3180d068b989
Revises: 6576bcd5ed63
Create Date: 2026-08-21 10:25:58.465167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3180d068b989'
down_revision: Union[str, None] = '6576bcd5ed63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('remember_me', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'remember_me')
    # ### end Alembic commands ###
