"""add object key to product images

Revision ID: 6576bcd5ed63
Revises: ae24b0f74bc3
Create Date: 2026-08-14 19:24:02.537688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6576bcd5ed63'
down_revision: Union[str, None] = 'ae24b0f74bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('object_key', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'product_images', ['object_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_images', type_='unique')
    op.drop_column('product_images', 'object_key')
    # ### end Alembic commands ###
