"""remove product image url in product table

Revision ID: 9b831f7f58a3
Revises: f3a5dee46c3c
Create Date: 2026-09-03 10:25:33.119099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b831f7f58a3'
down_revision: Union[str, None] = 'f3a5dee46c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column(
        "product_images",
        sa.Column(
            "url",
            sa.Text(),
            nullable=True,
        ),
    )

    op.execute(
        sa.text(
            """
            UPDATE product_images
            SET url = object_key
            """
        )
    )

    op.alter_column(
        "product_images",
        "url",
        existing_type=sa.Text(),
        nullable=False,
    )
