"""updated passcode_hash to unique and index true

Revision ID: ae24b0f74bc3
Revises: a2b415131a40
Create Date: 2026-08-11 18:57:13.434759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae24b0f74bc3'
down_revision: Union[str, None] = 'a2b415131a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'passcode_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_index(op.f('ix_users_passcode_hash'), 'users', ['passcode_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_passcode_hash'), table_name='users')
    op.alter_column('users', 'passcode_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
