"""removed passcode hash in users

Revision ID: f3a5dee46c3c
Revises: 50a131b4e17e
Create Date: 2026-08-31 12:25:50.084505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3a5dee46c3c'
down_revision: Union[str, None] = '50a131b4e17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_passcode_hash'), table_name='users')
    op.drop_column('users', 'passcode_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passcode_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_passcode_hash'), 'users', ['passcode_hash'], unique=True)
    # ### end Alembic commands ###
