name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest

    steps:
      - name: Download repository code
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v0.12.1
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install project dependencies
        run: uv sync --locked

      - name: Run pre-commit checks
        run: uv run pre-commit run --all-files
